on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
    create_release:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
          - name: Create Release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
            with:
              tag_name: ${{ github.ref }}
              release_name: Automice - MouseMover ${{ github.ref }}
              draft: false
              prerelease: false
          - shell: bash
            run: echo "${{ steps.create_release.outputs.upload_url }}" > release_upload_url.txt
          - name: Upload release url
            uses: actions/upload-artifact@v1
            with:
                name: release_url
                path: release_upload_url.txt

    build_release:
        name: Build and Release
        runs-on: ubuntu-latest
        needs: [create_release]

        steps:
          - name: Download release url
            uses: actions/download-artifact@v1
            with:
                name: release_url
          - shell: bash
            run: |
                export release_url=`cat release_url/release_upload_url.txt`
                echo "::set-env name=release_url::$release_url" 
                
          - uses: actions/checkout@v2
          - name: Build project # This would actually build your project, using zip for an example artifact
            run: |
              mkdir dist
              mv README.md dist/README.md
              zip -r my-artifact dist
   
          - name: Upload Release Asset
            id: upload_release_asset 
            uses: actions/upload-release-asset@v1
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                upload_url: ${{ env.release_url }}
                asset_path: ./my-artifact.zip
                asset_name: my-artifact.zip
                asset_content_type: application/zip

 
